use anyhow::{Context, Result};
use std::path::Path;

/// Generated filenames that agents must not edit directly.
const GENERATED_FILES: &[&str] = &["CLAUDE.md"];

pub fn run(hook_mode: bool) -> Result<()> {
    if !hook_mode {
        anyhow::bail!("guard is only used via --hook-mode");
    }

    let input = read_stdin()?;
    let value: serde_json::Value =
        serde_json::from_str(&input).context("failed to parse hook JSON from stdin")?;

    let file_path = value
        .get("tool_input")
        .and_then(|v| v.get("file_path"))
        .and_then(|v| v.as_str())
        .unwrap_or("");

    let filename = Path::new(file_path)
        .file_name()
        .and_then(|f| f.to_str())
        .unwrap_or("");

    if !GENERATED_FILES.contains(&filename) {
        return Ok(());
    }

    let output = serde_json::json!({
        "decision": "block",
        "reason": format!(
            "{} is generated by NRS — do not edit it directly. \
             If the context is wrong or incomplete, report a gap instead: \
             nrs gap report --type <type> --target <directory> --description \"what's missing or wrong\"",
            filename
        )
    });
    println!("{}", serde_json::to_string(&output)?);

    Ok(())
}

fn read_stdin() -> Result<String> {
    use std::io::Read;
    let mut buf = String::new();
    std::io::stdin()
        .read_to_string(&mut buf)
        .context("failed to read stdin")?;
    Ok(buf)
}
