use anyhow::{Context, Result};
use std::path::Path;

const NRS_CONTEXT: &str = include_str!("../../templates/nrs.context.md");

pub fn run(dir: &Path) -> Result<()> {
    let dir = dir
        .canonicalize()
        .with_context(|| format!("directory not found: {}", dir.display()))?;

    // Create nrs.context.md if it doesn't exist
    let nrs_context_path = dir.join("nrs.context.md");
    if !nrs_context_path.exists() {
        std::fs::write(&nrs_context_path, NRS_CONTEXT)?;
        println!("created nrs.context.md");
    } else {
        println!("nrs.context.md already exists");
    }

    let hook_path = dir.join(".git/hooks/pre-commit");

    // Check if git repo
    if !dir.join(".git").exists() {
        anyhow::bail!("not a git repository: {}", dir.display());
    }

    let hook_content = r#"#!/bin/sh
# NRS pre-commit hook — generated by `nrs init`

# Generate tool entry points
nrs generate all

# Validate context files
nrs validate

# Stage any generated files
git add -u
"#;

    if hook_path.exists() {
        let existing = std::fs::read_to_string(&hook_path)?;
        if existing.contains("nrs generate") {
            println!("pre-commit hook already contains NRS commands");
            return Ok(());
        }
        // Append to existing hook
        let mut content = existing;
        content.push_str("\n# NRS pre-commit hook — appended by `nrs init`\nnrs generate all\nnrs validate\ngit add -u\n");
        std::fs::write(&hook_path, content)?;
        println!("appended NRS commands to existing pre-commit hook");
    } else {
        std::fs::create_dir_all(dir.join(".git/hooks"))?;
        std::fs::write(&hook_path, hook_content)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&hook_path, std::fs::Permissions::from_mode(0o755))?;
        }
        println!("created pre-commit hook at .git/hooks/pre-commit");
    }

    Ok(())
}
