use crate::context::DirectoryContext;
use crate::generators::Generator;
use std::collections::BTreeMap;
use std::path::Path;

pub struct ClaudeGenerator;

const HEADER: &str = include_str!("../../templates/claude-header.txt");

const IGNORE_PATTERNS: &[&str] = &["*.context.md"];

impl Generator for ClaudeGenerator {
    fn name(&self) -> &str {
        "claude"
    }

    fn output_filename(&self) -> &str {
        "CLAUDE.md"
    }

    fn generate(&self, ctx: &DirectoryContext) -> String {
        let mut out = String::from(HEADER);
        out.push_str("\n\n");

        let ordered = order_files(ctx);

        let sections: Vec<&str> = ordered
            .iter()
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .collect();

        out.push_str(&sections.join("\n\n"));
        out.push('\n');
        out
    }

    fn ignore_patterns(&self) -> Vec<&str> {
        IGNORE_PATTERNS.to_vec()
    }

    fn apply_ignores(&self, project_root: &Path) -> anyhow::Result<()> {
        let settings_dir = project_root.join(".claude");
        std::fs::create_dir_all(&settings_dir)?;

        let settings_path = settings_dir.join("settings.local.json");
        let mut settings: BTreeMap<String, serde_json::Value> = if settings_path.exists() {
            let content = std::fs::read_to_string(&settings_path)?;
            serde_json::from_str(&content).unwrap_or_default()
        } else {
            BTreeMap::new()
        };

        let existing = settings
            .get("ignorePatterns")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();

        let mut patterns: Vec<String> = existing
            .iter()
            .filter_map(|v| v.as_str().map(String::from))
            .collect();

        for pat in IGNORE_PATTERNS {
            let s = pat.to_string();
            if !patterns.contains(&s) {
                patterns.push(s);
            }
        }

        settings.insert(
            "ignorePatterns".to_string(),
            serde_json::Value::Array(
                patterns
                    .into_iter()
                    .map(serde_json::Value::String)
                    .collect(),
            ),
        );

        let content = serde_json::to_string_pretty(&settings)?;
        std::fs::write(&settings_path, content)?;

        let relative = settings_path
            .strip_prefix(project_root)
            .unwrap_or(&settings_path);
        println!("updated {}", relative.display());

        Ok(())
    }
}

/// Order context files: corporate → team → domain → implementation → CONTEXT.md last.
fn order_files(ctx: &DirectoryContext) -> Vec<&str> {
    fn priority(name: &str) -> u8 {
        match name {
            "nrs.context.md" => 0,
            "corporate.context.md" => 1,
            "team.context.md" => 2,
            "project.context.md" => 3,
            "domain.context.md" => 4,
            "implementation.context.md" => 5,
            _ => 6,
        }
    }

    let mut entries: Vec<(&str, &str)> = ctx
        .files
        .iter()
        .map(|(name, content)| (name.as_str(), content.as_str()))
        .collect();

    entries.sort_by_key(|(name, _)| priority(name));
    entries.into_iter().map(|(_, content)| content).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn make_ctx(files: Vec<(&str, &str)>) -> DirectoryContext {
        let mut map = BTreeMap::new();
        for (name, content) in files {
            map.insert(name.to_string(), content.to_string());
        }
        DirectoryContext {
            dir: PathBuf::from("/tmp/test"),
            files: map,
        }
    }

    #[test]
    fn generate_includes_header() {
        let ctx = make_ctx(vec![("project.context.md", "# Project")]);
        let gen = ClaudeGenerator;
        let output = gen.generate(&ctx);
        assert!(output.starts_with("<!-- DO NOT EDIT — generated by NRS -->"));
    }

    #[test]
    fn generate_orders_nrs_first() {
        let ctx = make_ctx(vec![
            ("project.context.md", "# Project"),
            ("nrs.context.md", "# NRS"),
            ("corporate.context.md", "# Corp"),
        ]);
        let gen = ClaudeGenerator;
        let output = gen.generate(&ctx);

        let nrs_pos = output.find("# NRS").unwrap();
        let corp_pos = output.find("# Corp").unwrap();
        let project_pos = output.find("# Project").unwrap();

        assert!(nrs_pos < corp_pos);
        assert!(corp_pos < project_pos);
    }

    #[test]
    fn generate_orders_all_layers_correctly() {
        let ctx = make_ctx(vec![
            ("implementation.context.md", "# Impl"),
            ("domain.context.md", "# Domain"),
            ("team.context.md", "# Team"),
            ("corporate.context.md", "# Corp"),
            ("nrs.context.md", "# NRS"),
            ("project.context.md", "# Project"),
        ]);
        let gen = ClaudeGenerator;
        let output = gen.generate(&ctx);

        let positions: Vec<usize> = vec![
            output.find("# NRS").unwrap(),
            output.find("# Corp").unwrap(),
            output.find("# Team").unwrap(),
            output.find("# Project").unwrap(),
            output.find("# Domain").unwrap(),
            output.find("# Impl").unwrap(),
        ];

        for i in 1..positions.len() {
            assert!(
                positions[i - 1] < positions[i],
                "position {} should be before position {}",
                i - 1,
                i
            );
        }
    }

    #[test]
    fn generate_skips_empty_content() {
        let ctx = make_ctx(vec![
            ("project.context.md", "# Project"),
            ("corporate.context.md", ""),
        ]);
        let gen = ClaudeGenerator;
        let output = gen.generate(&ctx);
        assert!(!output.contains("\n\n\n\n"));
    }

    #[test]
    fn generate_empty_context() {
        let ctx = make_ctx(vec![]);
        let gen = ClaudeGenerator;
        let output = gen.generate(&ctx);
        assert!(output.starts_with("<!-- DO NOT EDIT"));
    }

    #[test]
    fn apply_ignores_creates_settings() {
        let tmp = TempDir::new().unwrap();
        let gen = ClaudeGenerator;
        gen.apply_ignores(tmp.path()).unwrap();

        let settings_path = tmp.path().join(".claude/settings.local.json");
        assert!(settings_path.exists());

        let content = std::fs::read_to_string(&settings_path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();
        let patterns = parsed["ignorePatterns"].as_array().unwrap();
        assert!(patterns.contains(&serde_json::Value::String("*.context.md".into())));
    }

    #[test]
    fn apply_ignores_merges_with_existing() {
        let tmp = TempDir::new().unwrap();
        let settings_dir = tmp.path().join(".claude");
        std::fs::create_dir_all(&settings_dir).unwrap();
        std::fs::write(
            settings_dir.join("settings.local.json"),
            r#"{"ignorePatterns":["node_modules"],"other":"preserved"}"#,
        )
        .unwrap();

        let gen = ClaudeGenerator;
        gen.apply_ignores(tmp.path()).unwrap();

        let content =
            std::fs::read_to_string(settings_dir.join("settings.local.json")).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();
        let patterns = parsed["ignorePatterns"].as_array().unwrap();
        assert!(patterns.contains(&serde_json::Value::String("node_modules".into())));
        assert!(patterns.contains(&serde_json::Value::String("*.context.md".into())));
        assert_eq!(parsed["other"], "preserved");
    }

    #[test]
    fn apply_ignores_idempotent() {
        let tmp = TempDir::new().unwrap();
        let gen = ClaudeGenerator;
        gen.apply_ignores(tmp.path()).unwrap();
        gen.apply_ignores(tmp.path()).unwrap();

        let content = std::fs::read_to_string(
            tmp.path().join(".claude/settings.local.json"),
        )
        .unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&content).unwrap();
        let patterns = parsed["ignorePatterns"].as_array().unwrap();
        let context_count = patterns
            .iter()
            .filter(|v| v.as_str() == Some("*.context.md"))
            .count();
        assert_eq!(context_count, 1);
    }
}
